name = "table-ai-backend"
main = "src/index.ts"
compatibility_date = "2024-03-20"

# Мы используем Cloudflare D1 для базы данных
[[d1_databases]]
binding = "DB" # Это имя переменной внутри кода воркера
database_name = "table-ai-db"
database_id = "117d51a6-630c-4d67-8a0d-1d2016b48d8a" # Вы получите этот ID, когда создадите БД в админке Cloudflare

[vars]
VK_CLIENT_ID = "52344009"
VK_SECURE_KEY = "fHKmdpHNo9GbSXMHAhdq"
JWT_SECRET = "ImA6Fin7LovlVTqJcOK98ILTjGPLAxqdiTU+GWKL+xE="
FRONTEND_URL = "https://klublocal.ddns.net"
